### ISSUE TITLE
Higher Difficulties Not Working

### ISSUE THREAD

**Issue by crypt0inf0** [CMarkley78/bitcoin_miner#5]
Hi, Using the difficulty upto `ffff001d` works fine. But when we increase the difficult for example to check against the latest block from the blockchain. It unable to find the correct nonce. 

How to fix it on [library.cu#L303](https://github.com/CMarkley78/bitcoin_miner/blob/main/GPU_Handler/library.cu#L303)

**Comment by CMarkley78** [comment]
Well its not guaranteed that there is a 32-bit nonce that solves a given block as the difficulty increases. That's the point of difficulty. Usually people will change the transactions they include in the block header they put together (which changes the Merkle Root), or I believe there is some data you can change within the coinbase transaction (which also changes to Merkle Root), which allows people to try an entirely new header.

**Comment by CMarkley78** [comment]
I haven't worked on this project in a while, but something you could try to see if this is really an issue with my code vs what I previously stated is to pull the header from an already solved block (meaning it's known that that header has a solution) then run this miner on that header. If it produces a nonce at the proper difficulty, you know everything's working fine. If it doesn't, maybe I'll pick the project back up.

**Comment by crypt0inf0** [comment]
this is the data from latest block [#851692](https://www.blockchain.com/explorer/blocks/btc/851692)
```
00206525
BC1F722993CF5580E4F954D8138A2E73CE847CFDC07500000000000000000000
979E1DFB9E6E3119BDBB61FE6E287F986D5F764AC8748362CE7CD89B4222E436
57E08F66
6D8A0317
```

`00206525BC1F722993CF5580E4F954D8138A2E73CE847CFDC07500000000000000000000979E1DFB9E6E3119BDBB61FE6E287F986D5F764AC8748362CE7CD89B4222E43657E08F666D8A0317`

This is not working.

**Comment by CMarkley78** [comment]
Interesting... thank you for the data! I've been pretty busy lately, but I'll see if I can make some time to figure this out. In the mean time (if you feel like toiling through my code), I have a sneaking suspicion it has to do with the 256-bit target generation function. I had a lot of trouble even finding solid documentation when I started the project, and it could be worth testing a bunch of values to see if anything weird happens with the target it generates. That will be the first thing I look at too. Thank you for the interest in my project here, I wasn't expecting to see any activity on this!

**Comment by crypt0inf0** [comment]
I use this function to make it work,
```
void setDifficulty(uint32_t bits, uint32_t *difficulty) {
    // Clear the difficulty array
    memset(difficulty, 0, 32);  // 32 bytes = 8 uint32_t elements

    // Extract exponent and significand
    uint32_t exponent = bits >> 24;
    uint32_t significand = bits & 0x00FFFFFF;

    // Calculate the position to place the significand
    uint32_t shift = 256 - (exponent * 8) - 24;  // 24 is the significand bit length
    uint32_t word_index = shift / 32;
    uint32_t bit_shift = shift % 32;

    // Place the significand
    uint64_t extended_significand = (uint64_t)significand << bit_shift;
    difficulty[word_index] = extended_significand & 0xFFFFFFFF;
    if (word_index < 7) {  // Ensure we don't write past the array
        difficulty[word_index + 1] = extended_significand >> 32;
    }
}
```
& modify the `search` function to use the above function on [library.cu#L303](https://github.com/CMarkley78/bitcoin_miner/blob/main/GPU_Handler/library.cu#L303)
```
 uint32_t target[8] = {0};
 // Use the new setDifficulty function
 setDifficulty(nbits, target);

    
 cudaMemcpyToSymbol(d_target, target, sizeof(uint32_t) * 8);
```

**Comment by CMarkley78** [comment]
Ok, that function works because it improperly generates the 256-bit target. It generates one that is way too high, so the miner is able to find a hash for it. The miner works properly, just because it doesn't find a solution for a specific header doesn't mean that it won't find a solution for any header. It just means that in the case of Bitcoin, you would need to change the random data in your coinbase transaction, hence changing the merkle root, hence changing your header, which would give you another 2^32 hashes to check using the miner.
